# Change these first
owner: LaunchQ # Your GitHub organization or username, where this repository lives
repo: LaunchQStatus-DEV # The name of this repository

sites:
  - name: LaunchQ Web App
    url: https://app-dev.launchq.ai/

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /LaunchQStatus-DEV
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: LaunchQ Status (DEV)
  introTitle: "**LaunchQ** Status (DEV)"
  introMessage: 
  navbar:
    - title: Status
      href: https://launchq.github.io/LaunchQStatus/
    - title: Status (DEV)
      href: /
    - title: LaunchQ
      href: https://app-dev.launchq.ai/

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
